name: Build application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm ci
    
    - name:
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'

    - name: Run on Android 
      run: cd android && ./gradlew assembleDebug