name: Build application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check secret
      env:
        TEST: ${{ secrets.TEST }}
      run: echo $TEST
    # - name: Setup Node.js
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: '22'
    #     cache: 'yarn'

    # - name: Install dependencies
    #   run: yarn install --frozen-lockfile
    
    # - name:
    #   uses: actions/setup-java@v4
    #   with:
    #     distribution: 'temurin'
    #     java-version: '17'
    #     cache: 'gradle'

    # - name: Run on Android 
    #   run: cd android && ./gradlew assembleDebug

  # build-ios:
  #   runs-on: macos-latest

  #   steps: 
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '22'
  #         cache: 'yarn'
  
  #     - name: Install dependencies
  #       run: yarn install --frozen-lockfile

  #     - name: Setup Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 3.3
  #         bundler-cache: true 

  #     - name: Install Ruby dependencies
  #       run: bundle install

  #     - name: Cache pods
  #       uses: actions/cache@v4
  #       id: pods-cache
  #       with:
  #         path: ./ios/Pods
  #         key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}

  #     - name: Install pods
  #       # if: steps.pods-cache.outputs.cache-hit != 'true' 
  #       shell: bash
  #       run: |
  #         cd ios
  #         bundle exec pod install

  #     - name: Build iOS app
  #       run: |
  #         cd ios
  #         xcodebuild build-for-testing \
  #           -scheme 'ViroStarterKit' \
  #           -allowProvisioningUpdates
